name: Deploy Strapi to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to server and pull latest changes
        run: |
          ssh -o StrictHostKeyChecking=no root@159.89.101.46 "cd /path/to/your/strapi/project && git pull origin main && npm install && pm2 restart strapi"
